#server:
#  port: 8083

spring:
#  mvc:
#    static-path-pattern: /assets/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/popeyeGym?serverTimezone=Asia/Seoul
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

  redis:
    host: localhost
    port: 6379


 # OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 45432640515-tsq2t1g1u9j1q75gg50q77asep4dsglt.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 14y3jI1FlYosIqcTu2Jn
            client-secret: AQbkPTx4bI
            scope:
              - name
              - email
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
          kakao:
            client-id: 33204fc5cbdce28928ebbae5ec3b3870
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        # Provider ??
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  # jwt
  jwt:
    secret: aXQncyB2ZXJ5IGxvbmcgbG9uZyBsb25nIHNlY3JldCBrZXk= # it's very long long long secret key
    access_token_expire_time: 1800000 #30분
    refresh_token_expire_time: 604800000 #7일

  oauth2:
    redirect_uri: http://localhost:3000/oauth2/redirect

# token
#app:
#  auth:
#    secretKey: 926D96C90030DD58429D2751AC1BDBBC
#    tokenExpirationMsec: 864000000
#  oauth2:
    # OAuth2 ???? ????? ?? ? ? ???? ?? ?? ??? ???? ???
    # ??? ?? ?????? /oauth2/authorize ???? ??? redirectUri???.
    # ??? ??? ??????? ? ???? ?? ??? ???? ????.
#    authorizedRedirectUris:
#      - http://localhost:3000/oauth2/redirect
#      - myandroidapp://oauth2/redirect
#      - myiosapp://oauth2/redirect


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
