logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher


  # jwt
  jwt:
    secret: aXQncyB2ZXJ5IGxvbmcgbG9uZyBsb25nIHNlY3JldCBrZXk= # it's very long long long secret key
    access_token_expire_time: 1800000 #30분
    refresh_token_expire_time: 604800000 #7일

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local



